core: remove manual renaming and let script handle rook to koor renaming
koor-tech/koor pull request #13
Opened 2022-10-06 12:27 UTC by ideepika

- rook-to-koor.sh: script for resolving patching rook to koor changes, this uses setting up a worktree with latest rook/master and mangling it to adopt koor conventions, creating a commit, before final merging.

Signed-off-by: Deepika Upadhyay <deepika@koor.tech>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://docs.koor.tech/docs/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://docs.koor.tech/docs/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/koor-tech/koor/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

2022-10-11 12:15 UTC, galexrt commented on rook-to-koor.sh
> +sed -i 's/v1\.10\../1\.0\.0/g' ${ROOKDIR}/Documentation/Upgrade/rook-upgrade.md
Maybe in the future we can use some `git` commands to get the latest tag of Koor, not needed for this PR.

2022-10-21 08:48 UTC, gauravsitlani commented
hey @ideepika the Codespell and ShellCheck tests are failing here, can you please look into it ?

2022-10-21 08:49 UTC, gauravsitlani commented
```
Error: ./rook-to-koor.sh:60: conflit ==> conflict
```

There's a spelling mistake here.

2022-10-21 08:50 UTC, gauravsitlani requested changes
```
Error: ./rook-to-koor.sh:60: conflit ==> conflict
```

There's a spelling mistake here.

2022-11-07 13:01 UTC, galexrt commented on rook-to-koor.sh
> +-e 's|rook/rook/issues|koor-tech/koor/issues|g' \
```suggestion
find "${ROOKDIR}" -type f ! -path "./.git/*" -exec sed -i \
    -e 's|rook/rook.github.io|koor-tech/docs.koor.tech|g' \
    -e 's|rook/rook/issues|koor-tech/koor/issues|g' \
```

2022-11-15 14:54 UTC, galexrt approved these changes

2022-11-16 18:26 UTC, galexrt commented
@gauravsitlani PTAL

2022-11-17 00:56 UTC, zalsader commented on rook-to-koor.sh
> +    -e 's/Rook*$ website/Koor website/g' \
What does this mean?

2022-11-17 02:12 UTC, zalsader approved these changes
Minor changes / questions

2022-11-18 09:09 UTC, ideepika commented on rook-to-koor.sh
> +# cd ${ROOKDIR} && git apply --reject --whitespace=fix ../rook-to-koor.patch
removed, thanks!

2022-11-18 09:10 UTC, ideepika commented on rook-to-koor.sh
> +    -e 's/Rook*$ website/Koor website/g' \
updated, as it didn't work, thanks!

2022-11-18 09:11 UTC, ideepika commented on rook-to-koor.sh
> +    -e 's/Rook*$ website/Koor website/g' \
```-  members. The build process will publish the documentation to the [Rook website](https://rook.io/docs/rook/latest/).
-* All storage providers are added to the [Rook.io website](https://rook.io/)
+  members. The build process will publish the documentation to the [Koor website](https://rook.io/docs/rook/latest/).
+* All storage providers are added to the [Koor website](https://rook.io/)```

2022-11-22 10:32 UTC, gauravsitlani approved these changes

2022-11-30 16:25 UTC, merged